(() => {
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const DPR=Math.min(devicePixelRatio||1,2); let W=innerWidth,H=innerHeight,last=performance.now();
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)} addEventListener('resize',resize);resize();

const world={w:3400,h:2400,waterY:1780};
const keys={},camera={x:0,y:0};
let time=8*60,day=1,modal=false,interior=null,currentNPC=null,bobber=null,fishing=null,museumTab='All';
let weather={type:'Clear',icon:'☀️',until:600};
let activeTool=null,toolUntil=0,soundOn=true,audioCtx=null,ambientGain=null;
let activeSlot=1,gameStarted=false,interiorPlayer={x:innerWidth/2,y:innerHeight-210};
let crops=[],friendUnlocks={},shopSeed=-1;
let townWorks={bridge:false,stairs:false,lighthouse:false},storyStage=0,cooked=0,npcMemories={},lastGamepadAction=0;
let gardens=[];
let fishShadows=spawnFishShadows();
let activeQuest={id:'museum',title:'A Place for Everything',text:'Donate one creature to the museum.',goal:1,progress:0,reward:120};

const fishCatalog=[
{name:'Bluegill',icon:'🐟',rarity:'Common',value:35,type:'Fish'},{name:'River Pike',icon:'🐠',rarity:'Uncommon',value:80,type:'Fish'},{name:'Moonfin',icon:'✨',rarity:'Rare',value:220,type:'Fish'},{name:'Glass Koi',icon:'🎏',rarity:'Rare',value:260,type:'Fish'},{name:'Silver Minnow',icon:'🐟',rarity:'Common',value:30,type:'Fish'},{name:'Sunset Trout',icon:'🐡',rarity:'Uncommon',value:105,type:'Fish'},{name:'Velvet Ray',icon:'🌙',rarity:'Rare',value:320,type:'Fish'}
];
const bugCatalog=[
{name:'Meadow Butterfly',icon:'🦋',rarity:'Common',value:40,type:'Bug'},{name:'Emerald Beetle',icon:'🪲',rarity:'Uncommon',value:95,type:'Bug'},{name:'Honey Moth',icon:'🦋',rarity:'Common',value:45,type:'Bug'},{name:'Prism Dragonfly',icon:'🪰',rarity:'Rare',value:240,type:'Bug'}
];
const fossilCatalog=[
{name:'Spiral Ammonite',icon:'🌀',rarity:'Common',value:90,type:'Fossil'},{name:'Ancient Fern',icon:'🌿',rarity:'Uncommon',value:145,type:'Fossil'},{name:'Tiny Raptor Claw',icon:'🦴',rarity:'Rare',value:310,type:'Fossil'}
];
const seaCatalog=[
{name:'Sea Star',icon:'⭐',rarity:'Common',value:70,type:'Sea'},{name:'Moon Jelly',icon:'🪼',rarity:'Uncommon',value:135,type:'Sea'},{name:'Pearl Oyster',icon:'🦪',rarity:'Uncommon',value:160,type:'Sea'},{name:'Crown Nautilus',icon:'🐚',rarity:'Rare',value:360,type:'Sea'}
];
const cropCatalog=[{name:'Turnip',icon:'🥬',value:75,type:'Crop'},{name:'Pumpkin',icon:'🎃',value:120,type:'Crop'},{name:'Strawberry',icon:'🍓',value:95,type:'Crop'}];
const allCatalog=[...fishCatalog,...bugCatalog,...fossilCatalog,...seaCatalog];
const furnitureCatalog=[
{name:'Cloud Sofa',icon:'🛋️',price:260,kind:'sofa'},{name:'Oak Table',icon:'🪵',price:180,kind:'table'},{name:'Reading Lamp',icon:'💡',price:120,kind:'lamp'},{name:'Leaf Rug',icon:'🍃',price:150,kind:'rug'},{name:'Record Player',icon:'🎶',price:340,kind:'music'},{name:'Potted Palm',icon:'🪴',price:110,kind:'plant'}
];

const player={x:1370,y:1050,r:16,speed:205,dir:0,step:0,coins:250,inventory:[],museum:[],ownedFurniture:[],placedFurniture:[],homeLevel:1,totalCaught:0,totalSold:0,flowersPlanted:0,
materials:{wood:2,stone:2,fiber:2},seeds:3,harvested:0,bagLevel:0,toolLevels:{rod:1,net:1,shovel:1},swimming:false,
look:{skin:'#f0c7a4',hair:'#593f36',shirt:'#405b9d',hat:'none'},houseStyle:{roof:'#537c96',body:'#f0d6b3'}};
const friendship={Pip:12,Mallow:10,Bruno:8,Juniper:6};
const requests={};

const npcs=[
{name:'Pip',emoji:'🐿️',x:1080,y:760,color:'#d69458',home:{x:900,y:560},lines:['Morning! The tide is perfect for fishing today.','I keep meaning to learn how to skip stones.','Your cottage is starting to feel like part of the neighborhood.']},
{name:'Mallow',emoji:'🐰',x:1630,y:725,color:'#e7b8cf',home:{x:1650,y:505},lines:['The flowers change the whole island when the light hits them.','I heard rare butterflies visit the west grove.','A cozy home needs at least one wildly unnecessary lamp.']},
{name:'Bruno',emoji:'🐻',x:760,y:1120,color:'#94735c',home:{x:610,y:930},lines:['I opened the boardwalk shop! Bring me duplicates and I’ll pay fair.','Fossils sometimes push little star cracks through the soil.','Furniture looks better after you have dragged it around six times.']},
{name:'Juniper',emoji:'🦉',x:2010,y:1060,color:'#8d78a9',home:null,lines:['Every donation becomes part of the Cove’s story.','Fish, bugs, fossils—I catalog all three collections.','A complete museum is less about perfection and more about curiosity.']}
];
const houses=[
{x:850,y:485,w:190,h:160,roof:'#d67855',body:'#f1d7aa',owner:'Pip'},
{x:1580,y:420,w:205,h:170,roof:'#cf7da0',body:'#f4dcc8',owner:'Mallow'},
{x:545,y:875,w:210,h:180,roof:'#6f8d7e',body:'#dfccb0',owner:'Bruno'},
{x:1880,y:850,w:355,h:265,roof:'#5c758c',body:'#efe0bd',owner:'Museum',museum:true},
{x:1250,y:610,w:205,h:175,roof:'#537c96',body:'#f0d6b3',owner:'You',playerHome:true},
{x:2150,y:560,w:255,h:195,roof:'#c58f4f',body:'#f6dfac',owner:'Shop',shop:true}
];
const paths=[{x:390,y:735,w:1790,h:120},{x:1230,y:470,w:120,h:910},{x:1785,y:760,w:120,h:390},{x:2100,y:680,w:260,h:95}];
const rocks=[{x:350,y:1260},{x:2240,y:710},{x:2360,y:1180},{x:300,y:620}];
const bridge={x:1240,y:1730,w:280,h:92};
const cliffs=[{x:2600,y:270,w:620,h:330},{x:2790,y:680,w:430,h:250}];
const secretTrees=Array.from({length:16},(_,i)=>({x:2760+(i%4)*120,y:1080+Math.floor(i/4)*120,s:.9+(i%3)*.08,fruit:true}));
const trees=Array.from({length:54},(_,i)=>({x:120+((i*197)%2450),y:120+((i*307)%1280),s:.78+((i*17)%40)/100})).filter(t=>!(t.x>430&&t.x<2450&&t.y>365&&t.y<1240));
const flowers=Array.from({length:95},(_,i)=>({x:120+((i*131)%2460),y:150+((i*211)%1280),c:['#f4b5c7','#f5d66c','#c9b3f6','#fff'][i%4]}));
let bugs=spawnBugs(),digSpots=spawnDigSpots();

function spawnBugs(){return Array.from({length:8},(_,i)=>({x:260+((i*331)%1850),y:350+((i*217)%820),kind:bugCatalog[i%bugCatalog.length],phase:i*.9,caught:false}));}
function spawnDigSpots(){return Array.from({length:5},(_,i)=>({x:390+((i*461)%1820),y:400+((i*293)%810),dug:false,kind:fossilCatalog[i%fossilCatalog.length]}));}
function spawnFishShadows(){return Array.from({length:10},(_,i)=>({x:230+((i*257)%2250),y:world.waterY+45+((i*37)%135),size:12+(i%4)*4,phase:i*.73,speed:10+(i%3)*4}));}
function saveKey(){return `cozyCoveSaveV4_slot${activeSlot}`}
function snapshot(){return {player,time,day,weather,activeQuest,friendship,requests,bugs,digSpots,gardens,crops,friendUnlocks,soundOn,townWorks,storyStage,cooked,npcMemories}}
function save(){if(gameStarted)localStorage.setItem(saveKey(),JSON.stringify(snapshot()))}
function applySave(s){if(!s)return;Object.assign(player,s.player||{});player.materials=Object.assign({wood:2,stone:2,fiber:2},player.materials||{});player.toolLevels=Object.assign({rod:1,net:1,shovel:1},player.toolLevels||{});player.look=Object.assign({skin:'#f0c7a4',hair:'#593f36',shirt:'#405b9d',hat:'none'},player.look||{});player.houseStyle=Object.assign({roof:'#537c96',body:'#f0d6b3'},player.houseStyle||{});time=s.time??time;day=s.day??day;weather=s.weather||weather;activeQuest=s.activeQuest||activeQuest;Object.assign(friendship,s.friendship||{});Object.assign(requests,s.requests||{});bugs=s.bugs||bugs;digSpots=s.digSpots||digSpots;gardens=s.gardens||gardens;crops=s.crops||[];friendUnlocks=s.friendUnlocks||{};soundOn=s.soundOn??soundOn;townWorks=Object.assign(townWorks,s.townWorks||{});storyStage=s.storyStage||0;cooked=s.cooked||0;npcMemories=s.npcMemories||{}}
function loadSlot(slot=activeSlot){activeSlot=slot;let raw=localStorage.getItem(saveKey());if(!raw&&slot===1){raw=localStorage.getItem('cozyCoveSaveV2');if(raw)localStorage.setItem(saveKey(),raw)}try{if(raw)applySave(JSON.parse(raw))}catch{}updateSlotSummary()}
function resetState(){localStorage.removeItem(saveKey());location.reload()}
setInterval(save,7000);

function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function ellipse(x,y,rx,ry,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function shadow(x,y,rx,ry,a=.16){ellipse(x,y,rx,ry,`rgba(23,55,43,${a})`)}
function worldToScreen(x,y){return{x:x-camera.x,y:y-camera.y}}
function near(a,b,d){return Math.hypot(a.x-b.x,a.y-b.y)<d}
function itemId(){return Date.now()+Math.random()}
function rarityColor(r){return r==='Rare'?'#8a67b8':r==='Uncommon'?'#4d8b8a':'#6b8e5d'}
function currentHour(){return Math.floor(time/60)}
function playTone(freq=520,dur=.09,vol=.035){if(!soundOn)return;try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function initAmbient(){if(!soundOn||ambientGain)return;try{if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();ambientGain=audioCtx.createGain();ambientGain.gain.value=.012;ambientGain.connect(audioCtx.destination);[174,261.6].forEach((f,i)=>{const o=audioCtx.createOscillator();o.type=i?'sine':'triangle';o.frequency.value=f;o.connect(ambientGain);o.start()})}catch{}}
function setTool(name,ms=520){activeTool=name;toolUntil=performance.now()+ms;playTone(name==='rod'?420:name==='net'?620:name==='shovel'?310:540,.06,.025)}
function npcSchedule(n){const h=currentHour();if(n.name==='Juniper')return {x:2010,y:1060,label:'Museum'};if(n.name==='Bruno')return h>=9&&h<18?{x:2180,y:815,label:'Boardwalk'}:h>=18?{x:700,y:1030,label:'Home'}:{x:780,y:1160,label:'Morning walk'};if(n.name==='Pip')return h<10?{x:1150,y:1435,label:'South Shore'}:h<17?{x:1040,y:760,label:'Village Green'}:{x:935,y:660,label:'Home'};if(n.name==='Mallow')return h<11?{x:430,y:780,label:'West Grove'}:h<19?{x:1530,y:760,label:'Flower Path'}:{x:1680,y:630,label:'Home'};return {x:n.x,y:n.y,label:'Around town'}}
function updateNPCSchedules(dt){npcs.forEach(n=>{const t=npcSchedule(n);n.scheduleLabel=t.label;n.x+=(t.x-n.x)*Math.min(1,dt*.7);n.y+=(t.y-n.y)*Math.min(1,dt*.7)})}

function drawSkyGround(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#98d77c');g.addColorStop(1,'#6eb76c');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.08;for(let i=0;i<80;i++){const x=(i*173-camera.x*.18)%W,y=(i*97-camera.y*.1)%H;ellipse(x,y,16,5,'#fff')}ctx.restore()}
function drawWater(){const y=world.waterY-camera.y;const g=ctx.createLinearGradient(0,y,0,H);g.addColorStop(0,'#73c9e1');g.addColorStop(1,'#3288a7');ctx.fillStyle=g;ctx.fillRect(0,y,W,H-y);ctx.save();ctx.globalAlpha=.25;ctx.strokeStyle='white';ctx.lineWidth=2.5;for(let row=0;row<10;row++){ctx.beginPath();for(let x=-80;x<W+80;x+=74){const yy=y+26+row*47+Math.sin((x+performance.now()/16+row*31)/44)*5;ctx.moveTo(x,yy);ctx.quadraticCurveTo(x+18,yy-6,x+38,yy)}ctx.stroke()}ctx.restore();drawFishShadows()}
function drawFishShadows(){ctx.save();for(const f of fishShadows){const s=worldToScreen(f.x,f.y);ctx.globalAlpha=.22;ctx.fillStyle='#173f52';ctx.beginPath();ctx.ellipse(s.x,s.y,f.size*1.5,f.size*.55,Math.sin(f.phase)*.08,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(s.x-f.size*1.4,s.y);ctx.lineTo(s.x-f.size*2.0,s.y-f.size*.55);ctx.lineTo(s.x-f.size*2.0,s.y+f.size*.55);ctx.closePath();ctx.fill()}ctx.restore()}
function drawPath(p){const s=worldToScreen(p.x,p.y);ctx.fillStyle='#d9c79d';rr(s.x,s.y,p.w,p.h,42);ctx.fill();ctx.globalAlpha=.18;for(let x=18;x<p.w;x+=58)ellipse(s.x+x,s.y+25+(x%38),3,2,'#7f6b4a');ctx.globalAlpha=1}
function drawTree(t){const s=worldToScreen(t.x,t.y),sc=t.s;shadow(s.x,s.y+25,38*sc,14*sc,.16);ctx.fillStyle='#8b6648';rr(s.x-9*sc,s.y-12*sc,18*sc,52*sc,8);ctx.fill();const grad=ctx.createRadialGradient(s.x-12*sc,s.y-42*sc,6,s.x,s.y-25*sc,56*sc);grad.addColorStop(0,'#a7e184');grad.addColorStop(1,'#3e8e59');ellipse(s.x-23*sc,s.y-38*sc,35*sc,33*sc,grad);ellipse(s.x+20*sc,s.y-35*sc,37*sc,35*sc,grad);ellipse(s.x,s.y-62*sc,42*sc,37*sc,grad);if(t.fruit||((t.x+t.y)|0)%3===0){ellipse(s.x-22*sc,s.y-44*sc,5*sc,5*sc,'#f0a95a');ellipse(s.x+18*sc,s.y-54*sc,5*sc,5*sc,'#f0a95a')}}
function drawFlower(f){const s=worldToScreen(f.x,f.y);ctx.strokeStyle='#3d8b56';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x,s.y-9);ctx.stroke();for(let a=0;a<Math.PI*2;a+=Math.PI/2)ellipse(s.x+Math.cos(a)*4,s.y-10+Math.sin(a)*4,3,3,f.c);ellipse(s.x,s.y-10,2.5,2.5,'#f2c94c')}
function drawHouse(h){if(h.playerHome&&player.houseStyle){h.roof=player.houseStyle.roof;h.body=player.houseStyle.body}const s=worldToScreen(h.x,h.y);shadow(s.x+h.w/2,s.y+h.h+18,h.w*.46,18,.2);ctx.fillStyle=h.body;rr(s.x,s.y+48,h.w,h.h-48,18);ctx.fill();ctx.fillStyle=h.roof;ctx.beginPath();ctx.moveTo(s.x-22,s.y+66);ctx.lineTo(s.x+h.w/2,s.y-20);ctx.lineTo(s.x+h.w+22,s.y+66);ctx.closePath();ctx.fill();ctx.fillStyle='#6f4d3a';rr(s.x+h.w/2-25,s.y+h.h-70,50,70,12);ctx.fill();ctx.fillStyle='#bfe7ed';rr(s.x+28,s.y+80,42,38,8);ctx.fill();rr(s.x+h.w-70,s.y+80,42,38,8);ctx.fill();let label='';if(h.museum)label='MUSEUM';if(h.shop)label='BOARDWALK';if(h.playerHome)label='YOUR COTTAGE';if(label){ctx.fillStyle='#f7f6ef';rr(s.x+h.w/2-72,s.y+28,144,32,16);ctx.fill();ctx.fillStyle='#40586c';ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.fillText(label,s.x+h.w/2,s.y+49);ctx.textAlign='left'}}
function drawNPC(n){const s=worldToScreen(n.x,n.y),walk=Math.sin(performance.now()/180+n.x*.01)*2;shadow(s.x,s.y+20,19,7,.18);ctx.save();ctx.translate(s.x,s.y+walk);ctx.fillStyle=n.color;rr(-18,-9,36,30,14);ctx.fill();ellipse(0,-20,15,14,'#fff2d8');ctx.font='25px serif';ctx.textAlign='center';ctx.fillText(n.emoji,0,-14);ctx.strokeStyle='rgba(70,50,40,.45)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-8,19);ctx.lineTo(-10,26);ctx.moveTo(8,19);ctx.lineTo(10,26);ctx.stroke();ctx.restore();ctx.textAlign='left';if(requests[n.name]&&!requests[n.name].done){ctx.font='900 18px system-ui';ctx.fillStyle='#f4c24f';ctx.fillText('!',s.x+19,s.y-37)}}
function drawPlayer(){const s=worldToScreen(player.x,player.y),walking=Math.abs(Math.sin(player.step));shadow(s.x,s.y+21,18,7,.2);ctx.save();ctx.translate(s.x,s.y);const lean=Math.sin(player.step)*.04;ctx.rotate(lean);ctx.strokeStyle='#334f83';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-7,12);ctx.lineTo(-8-Math.sin(player.step)*5,24);ctx.moveTo(7,12);ctx.lineTo(8+Math.sin(player.step)*5,24);ctx.stroke();ctx.fillStyle=player.look?.shirt||'#405b9d';rr(-15,-13,30,33,12);ctx.fill();ctx.strokeStyle=player.look?.skin||'#f0c7a4';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-13,-4);ctx.lineTo(-19,7+walking*2);ctx.moveTo(13,-4);ctx.lineTo(19,-7-walking*2);ctx.stroke();ellipse(0,-21,16,16,player.look?.skin||'#f0c7a4');ctx.fillStyle=player.look?.hair||'#593f36';ctx.beginPath();ctx.arc(0,-24,16,Math.PI,0);ctx.fill();ellipse(-5,-20,2.4,3,'white');ellipse(5,-20,2.4,3,'white');ellipse(-5,-20,1,1.7,'#29352f');ellipse(5,-20,1,1.7,'#29352f');if(player.look?.hat&&player.look.hat!=='none'){ctx.font='20px serif';ctx.textAlign='center';ctx.fillText(player.look.hat,0,-31);ctx.textAlign='left'}if(player.swimming){ctx.strokeStyle='rgba(255,255,255,.7)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,18,25,0,Math.PI*2);ctx.stroke()}drawHeldTool();ctx.restore()}
function drawHeldTool(){if(performance.now()>toolUntil){activeTool=null;return}ctx.save();ctx.translate(19,-5);ctx.rotate(-.45);ctx.lineWidth=3;ctx.strokeStyle='#6b4c34';if(activeTool==='rod'){ctx.beginPath();ctx.moveTo(0,12);ctx.lineTo(2,-30);ctx.stroke();ctx.strokeStyle='#333';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(2,-30);ctx.lineTo(28,-5);ctx.stroke()}else if(activeTool==='net'){ctx.beginPath();ctx.moveTo(0,14);ctx.lineTo(2,-24);ctx.stroke();ctx.strokeStyle='#d9e8df';ctx.lineWidth=3;ctx.beginPath();ctx.arc(2,-29,12,0,Math.PI*2);ctx.stroke()}else if(activeTool==='shovel'){ctx.beginPath();ctx.moveTo(0,14);ctx.lineTo(2,-24);ctx.stroke();ctx.fillStyle='#9ba7a2';ctx.beginPath();ctx.ellipse(2,-30,8,11,0,0,Math.PI*2);ctx.fill()}else if(activeTool==='plant'){ctx.font='20px serif';ctx.fillText('🌱',-8,-16)}ctx.restore()}
function drawRock(r){const s=worldToScreen(r.x,r.y);shadow(s.x,s.y+8,26,8,.18);ctx.fillStyle='#8c9a94';ctx.beginPath();ctx.moveTo(s.x-25,s.y+6);ctx.lineTo(s.x-15,s.y-18);ctx.lineTo(s.x+10,s.y-24);ctx.lineTo(s.x+28,s.y-2);ctx.lineTo(s.x+20,s.y+16);ctx.lineTo(s.x-15,s.y+18);ctx.closePath();ctx.fill()}
function drawBridge(){const s=worldToScreen(bridge.x,bridge.y);ctx.fillStyle='#b97c50';rr(s.x,s.y,bridge.w,bridge.h,12);ctx.fill();ctx.strokeStyle='rgba(80,45,25,.25)';for(let x=12;x<bridge.w;x+=24){ctx.beginPath();ctx.moveTo(s.x+x,s.y+4);ctx.lineTo(s.x+x,s.y+bridge.h-4);ctx.stroke()}}
function drawBugs(){for(const b of bugs){if(b.caught)continue;const s=worldToScreen(b.x,b.y);const bob=Math.sin(performance.now()/350+b.phase)*5;ctx.font='22px serif';ctx.textAlign='center';ctx.fillText(b.kind.icon,s.x,s.y+bob);ctx.textAlign='left'}}
function drawGardens(){for(const g of gardens){const s=worldToScreen(g.x,g.y);ellipse(s.x,s.y,12,5,'rgba(87,61,39,.28)');ctx.strokeStyle='#3d8b56';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x,s.y-13);ctx.stroke();const bloom=g.color||'#ffd36b';for(let a=0;a<Math.PI*2;a+=Math.PI/2)ellipse(s.x+Math.cos(a)*5,s.y-14+Math.sin(a)*5,3.5,3.5,bloom);ellipse(s.x,s.y-14,2.5,2.5,'#f3c95f')}}
function drawDigSpots(){for(const d of digSpots){if(d.dug)continue;const s=worldToScreen(d.x,d.y);ctx.strokeStyle='#8d704d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(s.x-9,s.y-6);ctx.lineTo(s.x+8,s.y+7);ctx.moveTo(s.x+9,s.y-6);ctx.lineTo(s.x-8,s.y+7);ctx.stroke()}}
function drawBobber(){if(!bobber)return;const s=worldToScreen(bobber.x,bobber.y),p=worldToScreen(player.x,player.y-8);ctx.strokeStyle='rgba(30,40,35,.65)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.quadraticCurveTo((p.x+s.x)/2,p.y-90,s.x,s.y);ctx.stroke();ellipse(s.x,s.y,6,4,'#f5f1e4');ellipse(s.x,s.y-3,4,4,'#e75858');if(fishing?.bite){const pulse=1+Math.sin(performance.now()/70)*.15;ctx.save();ctx.translate(s.x,s.y);ctx.scale(pulse,pulse);ctx.translate(-s.x,-s.y);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.lineWidth=2;for(let r=12;r<34;r+=10){ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
function drawWeather(){if(currentHour()>=19||currentHour()<5){ctx.save();ctx.globalAlpha=.7;for(let i=0;i<18;i++){const x=(i*167+Math.sin(performance.now()/900+i)*32)%W,y=80+((i*113)%Math.max(120,H-180));ellipse(x,y,2.2,2.2,'#ffe889')}ctx.restore()}if(weather.type==='Rain'){ctx.save();ctx.strokeStyle='rgba(210,235,255,.55)';ctx.lineWidth=1.5;for(let i=0;i<90;i++){const x=(i*71+performance.now()*.35)%W,y=(i*43+performance.now()*.6)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+18);ctx.stroke()}ctx.restore()}const h=currentHour();let alpha=0;if(h>=18)alpha=Math.min(.42,(h-18)*.08);if(h<6)alpha=.42;if(alpha){ctx.fillStyle=`rgba(34,45,82,${alpha})`;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=alpha+.1;for(let i=0;i<16;i++)ellipse((i*193)%W,(i*83)%Math.max(80,H*.55),1.5,1.5,'#fff');ctx.restore()}}
function drawInterior(){const museum=interior==='Museum',home=interior==='You',shop=interior==='Shop';ctx.fillStyle='#cfc09e';ctx.fillRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,museum?'#e9eee8':shop?'#f1dec1':'#f3e7cf');g.addColorStop(1,'#d8c29b');ctx.fillStyle=g;rr(60,45,W-120,H-90,28);ctx.fill();ctx.fillStyle='#9b7352';ctx.fillRect(70,H-170,W-140,90);for(let x=90;x<W-90;x+=55){ctx.strokeStyle='rgba(70,45,30,.14)';ctx.beginPath();ctx.moveTo(x,H-168);ctx.lineTo(x,H-82);ctx.stroke()}ctx.fillStyle='#fff5dc';rr(W/2-60,78,120,95,16);ctx.fill();ctx.fillStyle='#8cc6de';rr(W/2-49,89,98,73,10);ctx.fill();ctx.fillStyle='#5d4b3d';ctx.font='800 20px system-ui';ctx.fillText(museum?'Archive Hall':shop?'Bruno’s Boardwalk':home?'Your Cottage':`${interior}'s Home`,100,102);ctx.font='14px system-ui';ctx.fillText('Press E near the door to go outside',100,130);
 if(museum){ctx.fillStyle='#d8e7e5';rr(90,175,W-180,H-320,28);ctx.fill();ctx.fillStyle='#5c758c';ctx.font='800 15px system-ui';ctx.fillText('AQUARIUM',130,205);ctx.fillText('INSECTARIUM',W/2-65,205);ctx.fillText('FOSSIL HALL',W-260,205);ctx.fillStyle='#fff';rr(W/2-100,H-165,200,58,18);ctx.fill();ctx.fillStyle='#40586c';ctx.textAlign='center';ctx.fillText('Curator Desk · press E nearby',W/2,H-130);ctx.textAlign='left';for(let i=0;i<Math.min(12,player.museum.length);i++){const col=i%5,row=Math.floor(i/5),x=120+col*155,y=210+row*190;ctx.fillStyle='#9d7d59';rr(x,y,110,150,12);ctx.fill();ctx.fillStyle='#dbe9e8';rr(x+14,y+14,82,78,10);ctx.fill();ctx.font='32px serif';ctx.textAlign='center';ctx.fillText(player.museum[i].icon,x+55,y+65);ctx.textAlign='left';ctx.font='11px system-ui';ctx.fillStyle='#3f514a';ctx.fillText(player.museum[i].name,x+10,y+118)}}
 if(home){drawPlacedFurniture();ctx.font='24px serif';ctx.fillText('🪟',W-150,130)} if(shop){ctx.fillStyle='#a97f57';rr(W/2-210,H/2-40,420,110,20);ctx.fill();ctx.fillStyle='#fff3d5';ctx.font='800 18px system-ui';ctx.textAlign='center';ctx.fillText('Browse with E near the counter',W/2,H/2+18);ctx.textAlign='left';ctx.font='34px serif';ctx.fillText('🪴',120,H-210);ctx.fillText('📦',W-170,H-210)} if(!museum&&!home&&!shop){ctx.font='36px serif';const decor=interior==='Pip'?['🎣','🪨','🧢']:interior==='Mallow'?['🌷','🧶','🫖']:['🪴','📚','🕯️'];decor.forEach((d,i)=>ctx.fillText(d,150+i*125,H/2));}}
function drawPlacedFurniture(){const slots=[{x:.25,y:.42},{x:.42,y:.38},{x:.6,y:.43},{x:.72,y:.36},{x:.36,y:.6},{x:.58,y:.62}];player.placedFurniture.forEach((f,i)=>{const s=slots[i%slots.length];ctx.font='42px serif';ctx.textAlign='center';ctx.fillText(f.icon,W*s.x,H*s.y);ctx.textAlign='left'})}
function drawPlayerInterior(){const x=interior==='Museum'?interiorPlayer.x:W/2,y=interior==='Museum'?interiorPlayer.y:H-170;shadow(x,y,18,7,.2);ctx.fillStyle=player.look?.shirt||'#405b9d';rr(x-14,y-34,28,31,12);ctx.fill();ellipse(x,y-41,15,15,player.look?.skin||'#f0c7a4');if(player.look?.hat&&player.look.hat!=='none'){ctx.font='18px serif';ctx.textAlign='center';ctx.fillText(player.look.hat,x,y-52);ctx.textAlign='left'}}


function seasonForDay(){const s=['Spring','Summer','Autumn','Winter'][Math.floor((day-1)/7)%4];return s}
function seasonIcon(){return {Spring:'🌱',Summer:'☀️',Autumn:'🍂',Winter:'❄️'}[seasonForDay()]}
function drawCliffs(){for(const c of cliffs){const s=worldToScreen(c.x,c.y);ctx.fillStyle='#78916d';rr(s.x,s.y,c.w,c.h,46);ctx.fill();ctx.fillStyle='#a2b590';rr(s.x+18,s.y+18,c.w-36,c.h-60,38);ctx.fill();ctx.fillStyle='#64775f';for(let x=35;x<c.w-30;x+=90)ellipse(s.x+x,s.y+c.h-18,34,15,'#657b61')}}
function drawCrops(){for(const c of crops){const s=worldToScreen(c.x,c.y),p=Math.min(1,(time+c.ageOffset-c.planted)/180);ellipse(s.x,s.y,14,6,'rgba(77,55,38,.3)');ctx.font=`${18+Math.floor(p*10)}px serif`;ctx.textAlign='center';ctx.fillText(p>=1?c.icon:'🌱',s.x,s.y-8);ctx.textAlign='left'}}
function cropReady(c){return (time+c.ageOffset-c.planted)>=180}
function nearestCrop(){return crops.find(c=>Math.hypot(player.x-c.x,player.y-c.y)<72&&cropReady(c))}
function gather(){if(interior||modal||player.swimming)return;const nearTree=[...trees,...secretTrees].find(t=>Math.hypot(player.x-t.x,player.y-t.y)<90);if(nearTree){player.materials.wood+=(player.toolLevels?.shovel||1);if(nearTree.fruit||Math.random()<.6){addItem({name:'Orchard Pear',icon:'🍐',rarity:'Common',value:55,type:'Fruit',id:itemId()})}toast(`Gathered wood${nearTree.fruit?' and fruit':''}`);playTone(430,.07,.03);save();return}const r=rocks.find(r=>Math.hypot(player.x-r.x,player.y-r.y)<90);if(r){player.materials.stone+=(player.toolLevels?.shovel||1);toast('Gathered stone');save();return}if(player.x<700){player.materials.fiber+=1;toast('Gathered meadow fiber');save();return}toast('Try near a tree, rock, or the west grove')}
function toggleSwimDive(){if(interior||modal)return;if(!player.swimming){if(player.y<world.waterY-70){toast('Head to the south shore to swim');return}player.swimming=true;player.y=world.waterY+65;toast('Swimming · press V to dive, E near shore to get out');return}const pool=seaCatalog;const q={...pool[Math.floor(Math.random()*pool.length)],id:itemId()};if(addItem(q)){player.totalCaught++;toast(`Dove up ${q.name}!`);updateQuest('catch',1);playTone(760,.11,.04);save()}}
function plantCrop(){if(interior||modal||player.swimming)return;if(player.seeds<=0){toast('No seeds — Bruno rotates seed packets daily');return}if(player.y>world.waterY-90){toast('Plant crops on grass');return}if(crops.some(c=>Math.hypot(c.x-player.x,c.y-player.y)<44)){toast('That patch is already planted');return}const kind=cropCatalog[(day+crops.length)%cropCatalog.length];player.seeds--;crops.push({x:player.x+Math.cos(player.dir)*30,y:player.y+Math.sin(player.dir)*30,name:kind.name,icon:kind.icon,value:kind.value,planted:time,ageOffset:0});setTool('plant',650);toast(`Planted ${kind.name} seeds`);save()}
function harvestCrop(c){const i=crops.indexOf(c);if(i<0)return;const q={name:c.name,icon:c.icon,rarity:'Common',value:c.value,type:'Crop',id:itemId()};if(addItem(q)){crops.splice(i,1);player.harvested=(player.harvested||0)+1;toast(`Harvested ${c.name}!`);save()}}
function toolCost(level){return {wood:2+level*2,stone:1+level,coins:180*level}}
function craftTool(name){player.toolLevels=player.toolLevels||{rod:1,net:1,shovel:1};const lvl=player.toolLevels[name]||1;if(lvl>=3){toast('That tool is already masterwork');return}const c=toolCost(lvl);if(player.materials.wood<c.wood||player.materials.stone<c.stone||player.coins<c.coins){toast('You need more materials');return}player.materials.wood-=c.wood;player.materials.stone-=c.stone;player.coins-=c.coins;player.toolLevels[name]++;toast(`${name[0].toUpperCase()+name.slice(1)} upgraded to Lv. ${player.toolLevels[name]}!`);renderCraft();save()}
window.craftTool=craftTool;
function craftBag(){const level=player.bagLevel||0;if(level>=2){toast('Backpack is fully expanded');return}const cost=300+level*350;if(player.materials.fiber<4+level*3||player.coins<cost){toast('Need more fiber and shells');return}player.materials.fiber-=4+level*3;player.coins-=cost;player.bagLevel=level+1;toast(`Backpack expanded to ${24+player.bagLevel*8} slots`);renderCraft();save()}
window.craftBag=craftBag;
function buySeeds(){const price=80;if(player.coins<price){toast('Not enough shells');return}player.coins-=price;player.seeds+=5;toast('Bought 5 seed packets');renderShop();save()}
window.buySeeds=buySeeds;
function setLook(part,value){player.look[part]=value;renderWardrobe();save()} window.setLook=setLook;
function setExterior(roof,body){player.houseStyle={roof,body};renderHome();save()} window.setExterior=setExterior;
function dailyShopItems(){const start=(day*2)%furnitureCatalog.length;return [furnitureCatalog[start],furnitureCatalog[(start+1)%furnitureCatalog.length],furnitureCatalog[(start+3)%furnitureCatalog.length]]}
function checkFriendUnlock(name){const f=friendship[name]||0;for(const t of [25,50,75]){const k=`${name}_${t}`;if(f>=t&&!friendUnlocks[k]){friendUnlocks[k]=true;if(t===25){player.seeds+=3;toast(`${name} gave you 3 seed packets!`)}else if(t===50){player.materials.fiber+=5;toast(`${name} taught you a crafting trick · +5 fiber`)}else{player.coins+=350;toast(`${name}'s friendship gift · +✦ 350`)}}}}
function renderCraft(){const m=player.materials||{wood:0,stone:0,fiber:0};document.getElementById('materialStats').innerHTML=`<span class="resourceChip">🪵 Wood ${m.wood}</span><span class="resourceChip">🪨 Stone ${m.stone}</span><span class="resourceChip">🌾 Fiber ${m.fiber}</span><span class="resourceChip">🌱 Seeds ${player.seeds||0}</span>`;const names=[['rod','🎣'],['net','🦋'],['shovel','⛏️']];document.getElementById('craftGrid').innerHTML=names.map(([n,e])=>{const l=player.toolLevels?.[n]||1,c=toolCost(l);return `<div class="card"><div class="icon">${e}</div><h3>${n[0].toUpperCase()+n.slice(1)} · Lv. ${l}</h3><p>${l>=3?'Masterwork':`Upgrade: 🪵 ${c.wood} · 🪨 ${c.stone} · ✦ ${c.coins}`}</p><button ${l>=3?'disabled':''} onclick="craftTool('${n}')">${l>=3?'Maxed':'Upgrade'}</button></div>`}).join('')+`<div class="card"><div class="icon">🎒</div><h3>Backpack · ${24+(player.bagLevel||0)*8} slots</h3><p>Expand using fiber and shells.</p><button onclick="craftBag()">Expand</button></div>`}
function renderWardrobe(){const looks={skin:['#f3d1b5','#d9a77c','#a66f4f','#704a39'],hair:['#3d2b27','#7a4d2a','#d4a15e','#23282f'],shirt:['#405b9d','#6f9f70','#c56d7d','#d7a542']};document.getElementById('creatorPreview').innerHTML=`<div style="font-size:58px">${player.look.hat==='none'?'🙂':player.look.hat+'🙂'}</div>`;document.getElementById('wardrobeGrid').innerHTML=Object.entries(looks).map(([part,vals])=>`<div class="creatorGroup"><b>${part[0].toUpperCase()+part.slice(1)}</b><div class="swatches">${vals.map(v=>`<button class="swatch ${player.look[part]===v?'active':''}" style="background:${v}" onclick="setLook('${part}','${v}')"></button>`).join('')}</div></div>`).join('')+`<div class="creatorGroup"><b>Hat</b><div class="swatches">${['none','🧢','👒','🎓'].map(v=>`<button class="emojiChoice ${player.look.hat===v?'active':''}" onclick="setLook('hat','${v}')">${v==='none'?'—':v}</button>`).join('')}</div></div>`}
function renderFarm(){document.getElementById('farmStats').innerHTML=`<div class="stat"><strong>${player.seeds||0}</strong><span>Seeds</span></div><div class="stat"><strong>${crops.length}</strong><span>Growing</span></div><div class="stat"><strong>${player.harvested||0}</strong><span>Harvested</span></div><div class="stat"><strong>${seasonIcon()}</strong><span>${seasonForDay()}</span></div>`;document.getElementById('cropGrid').innerHTML=crops.length?crops.map(c=>`<div class="card"><div class="icon">${cropReady(c)?c.icon:'🌱'}</div><h3>${c.name}</h3><p>${cropReady(c)?'Ready to harvest':'Growing…'}</p></div>`).join(''):'<div class="empty">No crops planted yet. Buy seeds from Bruno and press G on grass.</div>'}
function updateSlotSummary(){const e=document.getElementById('slotSummary');if(!e)return;const raw=localStorage.getItem(saveKey());if(!raw){e.textContent=`Empty local save · Slot ${activeSlot}`;document.getElementById('continueGame').textContent='Start';return}try{const s=JSON.parse(raw);e.textContent=`Slot ${activeSlot} · Day ${s.day||1} · ✦ ${s.player?.coins||0} · Museum ${s.player?.museum?.length||0}/${allCatalog.length}`;document.getElementById('continueGame').textContent='Continue'}catch{e.textContent=`Slot ${activeSlot}`}}
function startGame(){loadSlot(activeSlot);gameStarted=true;document.getElementById('titleScreen').classList.add('hidden');renderInventory();renderMuseum();renderShop();renderJournal();renderHome();renderCraft();renderWardrobe();renderFarm();}
function update(dt){if(!gameStarted)return;if(!modal&&interior==='Museum'){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){const l=Math.hypot(dx,dy);interiorPlayer.x=Math.max(90,Math.min(W-90,interiorPlayer.x+dx/l*180*dt));interiorPlayer.y=Math.max(140,Math.min(H-105,interiorPlayer.y+dy/l*180*dt));}}
else if(!modal&&!interior){time+=dt*2.2;if(time>=1440){time-=1440;day++;crops.forEach(c=>c.ageOffset+=1440);newDay()}weather.until-=dt;if(weather.until<=0)rollWeather();let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){const l=Math.hypot(dx,dy);dx/=l;dy/=l;const maxY=player.swimming?world.h-45:world.waterY+20;const minY=player.swimming?world.waterY+15:45;player.x=Math.max(45,Math.min(world.w-45,player.x+dx*player.speed*(player.swimming?.65:1)*dt));player.y=Math.max(minY,Math.min(maxY,player.y+dy*player.speed*(player.swimming?.65:1)*dt));player.step+=dt*11;player.dir=Math.atan2(dy,dx)}updateNPCSchedules(dt);fishShadows.forEach((f,i)=>{f.x+=Math.sin(f.phase)*f.speed*dt;f.phase+=dt*.7;if(f.x<120)f.x=3150;if(f.x>3250)f.x=150});camera.x+=(player.x-W/2-camera.x)*Math.min(1,dt*5);camera.y+=(player.y-H/2-camera.y)*Math.min(1,dt*5);camera.x=Math.max(0,Math.min(world.w-W,camera.x));camera.y=Math.max(0,Math.min(world.h-H,camera.y));if(fishing){fishing.t-=dt;if(!fishing.bite&&fishing.t<0){fishing.bite=true;fishing.t=1.15+((player.toolLevels?.rod||1)-1)*.35;playTone(780,.11,.045);toast('Bite! Press F!')}else if(fishing.bite&&fishing.t<0){fishing=null;bobber=null;toast('It got away…')}}}}
function render(){ctx.clearRect(0,0,W,H);if(interior){drawInterior();drawPlayerInterior();drawWeather();drawHUD();return}drawSkyGround();drawCliffs();paths.forEach(drawPath);flowers.forEach(drawFlower);trees.forEach(drawTree);secretTrees.forEach(drawTree);drawCrops();houses.forEach(drawHouse);rocks.forEach(drawRock);drawDigSpots();drawGardens();drawBugs();drawWater();drawBridge();npcs.forEach(drawNPC);drawBobber();drawPlayer();drawWeather();drawHUD()}
function drawHUD(){const hh=Math.floor(time/60),mm=Math.floor(time%60),ampm=hh>=12?'PM':'AM',hr=((hh+11)%12)+1;document.getElementById('clock').textContent=`Day ${day} · ${hr}:${String(mm).padStart(2,'0')} ${ampm}`;document.getElementById('coins').textContent=`✦ ${player.coins}`;document.getElementById('weather').textContent=`${weather.icon} ${weather.type}`;document.getElementById('season').textContent=`${seasonIcon()} ${seasonForDay()}`;document.getElementById('questTitle').textContent=activeQuest.title;document.getElementById('questText').textContent=`${activeQuest.text} Reward: ✦ ${activeQuest.reward}`;document.getElementById('questProgress').style.width=`${Math.min(100,activeQuest.progress/activeQuest.goal*100)}%`;const n=getNearby();const p=document.getElementById('prompt');if(n){p.classList.remove('hidden');p.textContent=n.label}else p.classList.add('hidden')}

function getNearby(){
  if(interior==='Museum'){if(Math.hypot(interiorPlayer.x-W/2,interiorPlayer.y-(H-135))<120)return {type:'museumDesk',label:'E · Browse collection'};if(interiorPlayer.y>H-145)return {type:'exit',label:'E · Leave museum'};return null}
  if(interior) return {type:'exit',label:interior==='Shop'?'E · Browse shop / leave':'E · Leave'};
  const ready=nearestCrop();if(ready)return {type:'crop',crop:ready,label:`E · Harvest ${ready.name}`};
  for(const n of npcs){
    if(Math.hypot(player.x-n.x,player.y-n.y)<72) return {type:'npc',npc:n,label:`E · Talk to ${n.name}`};
  }
  for(const b of bugs){
    if(!b.caught&&Math.hypot(player.x-b.x,player.y-b.y)<78) return {type:'bug',bug:b,label:`B · Catch ${b.kind.name}`};
  }
  for(const d of digSpots){
    if(!d.dug&&Math.hypot(player.x-d.x,player.y-d.y)<80) return {type:'dig',dig:d,label:'X · Dig fossil spot'};
  }
  for(const h of houses){
    const dx=h.x+h.w/2,dy=h.y+h.h;
    if(Math.hypot(player.x-dx,player.y-dy)<88){
      if(h.shop) return {type:'shop',house:h,label:'E · Enter Boardwalk'};
      const label=h.owner==='Museum'?'Museum':h.owner==='You'?'your cottage':h.owner+"'s home";
      return {type:'house',house:h,label:`E · Enter ${label}`};
    }
  }
  if(player.swimming&&player.y<world.waterY+100)return {type:'shoreExit',label:'E · Return to shore'};if(player.y>world.waterY-100&&player.y<world.waterY+25) return {type:'shore',label:'F · Fish · V · Swim'};
  return null;
}
function interact(){if(!document.getElementById('dialogue').classList.contains('hidden')){advanceDialogue();return}const n=getNearby();if(interior==='Museum'){if(n?.type==='museumDesk'){toggle('museum');return}if(n?.type==='exit'){interior=null;modal=false;return}return}if(interior){if(interior==='Shop'){toggle('shop');return}interior=null;modal=false;return}if(!n)return;if(n.type==='crop'){harvestCrop(n.crop);return}if(n.type==='shoreExit'){player.swimming=false;player.y=world.waterY-65;toast('Back on shore');return}if(n.type==='npc')openDialogue(n.npc);else if(n.type==='house'){interior=n.house.owner;modal=false;if(interior==='Museum'){interiorPlayer={x:W/2,y:H-180};toast('Walk through the galleries · curator desk is ahead')}if(interior==='You')toast('Home sweet home. Press H to decorate.')}else if(n.type==='shop'){interior='Shop';modal=false;toggle('shop')}}
function openDialogue(n){currentNPC=n;const memoryLine=rememberNPC(n);friendship[n.name]=Math.min(100,(friendship[n.name]||0)+1);checkFriendUnlock(n.name);if(!requests[n.name]&&n.name!=='Juniper'&&Math.random()<.45)createRequest(n.name);const req=requests[n.name];let line=memoryLine||n.lines[Math.floor(Math.random()*n.lines.length)];if(req&&!req.done){const idx=player.inventory.findIndex(x=>x.type===req.type);if(idx>=0){const item=player.inventory[idx];player.inventory.splice(idx,1);req.done=true;friendship[n.name]=Math.min(100,friendship[n.name]+8);player.coins+=req.reward;line=`You found a ${req.type.toLowerCase()} for me! ${item.name} is perfect. Here—take ✦ ${req.reward}.`;toast(`Request complete · +8 friendship`)}else line=`Small favor? I’m looking for any ${req.type.toLowerCase()}. Bring one by if you spot it.`}document.getElementById('portrait').textContent=n.emoji;document.getElementById('speaker').textContent=n.name;document.getElementById('friendship').textContent=`♥ ${friendship[n.name]||0}`;document.getElementById('line').textContent=line;document.getElementById('dialogue').classList.remove('hidden');modal=true;renderJournal();save()}
function advanceDialogue(){document.getElementById('dialogue').classList.add('hidden');modal=false;currentNPC=null}
function createRequest(name){const types=['Fish','Bug','Fossil'];requests[name]={type:types[(day+name.length)%types.length],reward:90+((name.length*17+day*23)%90),done:false,day}}

function cast(){if(interior||modal||player.swimming)return;setTool('rod',900);if(fishing){if(fishing.bite){const pool=weather.type==='Rain'?[...fishCatalog,...fishCatalog.filter(x=>x.rarity!=='Common')]:fishCatalog;const cat={...pool[Math.floor(Math.random()*pool.length)],id:itemId()};if(addItem(cat)){player.totalCaught++;toast(`Caught ${cat.name}!`);updateQuest('catch',1)}fishing=null;bobber=null;save()}else{fishing=null;bobber=null;toast('Reeled in early')}return}if(player.y>world.waterY-120){bobber={x:player.x+Math.cos(player.dir)*45,y:world.waterY+72};fishing={t:1.1+Math.random()*2.7,bite:false};toast('Waiting for a bite…')}else toast('Move closer to the water')}
function catchBug(){if(interior||modal)return;setTool('net',520);const b=bugs.find(x=>!x.caught&&Math.hypot(player.x-x.x,player.y-x.y)<86+(player.toolLevels?.net||1)*8);if(!b){toast('No bug in net range');return}if(addItem({...b.kind,id:itemId()})){b.caught=true;player.totalCaught++;toast(`Caught ${b.kind.name}!`);updateQuest('catch',1);save()}}
function dig(){if(interior||modal)return;setTool('shovel',620);const d=digSpots.find(x=>!x.dug&&Math.hypot(player.x-x.x,player.y-x.y)<88);if(!d){toast('Look for a star-shaped crack in the soil');return}if(addItem({...d.kind,id:itemId()})){d.dug=true;player.materials.stone+=(player.toolLevels?.shovel||1)-1;player.totalCaught++;toast(`Unearthed ${d.kind.name}!`);updateQuest('dig',1);save()}}
function plant(){plantCrop()}
function addItem(item){if(player.inventory.length>=24+(player.bagLevel||0)*8){toast('Your backpack is full');return false}player.inventory.push(item);renderInventory();return true}

function donate(i){const it=player.inventory[i];if(!it)return;if(player.museum.some(x=>x.name===it.name)){toast('The museum already has one');return}player.museum.push({...it});player.inventory.splice(i,1);toast(`${it.name} donated!`);updateQuest('museum',1);renderInventory();renderMuseum();save()}
window.donate=donate;
function sell(i){const it=player.inventory[i];if(!it)return;player.coins+=it.value;player.totalSold+=it.value;player.inventory.splice(i,1);toast(`Sold ${it.name} for ✦ ${it.value}`);updateQuest('sell',it.value);renderInventory();renderShop();save()}
window.sell=sell;
function buyFurniture(i){const f=furnitureCatalog[i];if(player.ownedFurniture.some(x=>x.name===f.name)){toast('You already own that piece');return}if(player.coins<f.price){toast('Not enough shells');return}player.coins-=f.price;player.ownedFurniture.push({...f});toast(`${f.name} delivered to your cottage`);renderShop();renderHome();save()}
window.buyFurniture=buyFurniture;
function placeFurniture(i){const f=player.ownedFurniture[i];if(!f)return;const exists=player.placedFurniture.findIndex(x=>x.name===f.name);if(exists>=0){player.placedFurniture.splice(exists,1);toast(`${f.name} put back in storage`)}else{if(player.placedFurniture.length>=4+player.homeLevel*2){toast('Upgrade your cottage for more display space');return}player.placedFurniture.push({...f});toast(`${f.name} placed`)}renderHome();save()}
window.placeFurniture=placeFurniture;
function upgradeHome(){if(player.homeLevel>=3)return;const cost=650*player.homeLevel;if(player.coins<cost){toast('You need more shells for that expansion');return}player.coins-=cost;player.homeLevel++;toast(`Cottage expanded to Level ${player.homeLevel}!`);playTone(740,.18,.05);renderHome();save()}
window.upgradeHome=upgradeHome;

function updateQuest(kind,amount){if(activeQuest.id!==kind)return;activeQuest.progress+=amount;if(activeQuest.progress>=activeQuest.goal){player.coins+=activeQuest.reward;toast(`Daily goal complete! +✦ ${activeQuest.reward}`);activeQuest=nextQuest();save()}}
function nextQuest(){const options=[
{id:'catch',title:'Field Notes',text:'Catch 3 creatures around the island.',goal:3,progress:0,reward:140},
{id:'sell',title:'Boardwalk Business',text:'Sell ✦ 200 worth of discoveries.',goal:200,progress:0,reward:160},
{id:'dig',title:'Under Our Feet',text:'Unearth 2 fossils.',goal:2,progress:0,reward:170},
{id:'museum',title:'Curator’s Choice',text:'Donate 2 new specimens.',goal:2,progress:0,reward:180}
];return {...options[(day+Math.floor(Math.random()*options.length))%options.length]}}
function newDay(){bugs=spawnBugs();digSpots=spawnDigSpots();fishShadows=spawnFishShadows();for(const k of Object.keys(requests))if(requests[k].day<day)delete requests[k];activeQuest=nextQuest();rollWeather();toast(day%7===0?`Day ${day} · Lantern Festival tonight!`:`Day ${day} begins · ${seasonForDay()}`);save()}
function rollWeather(){const r=Math.random();weather=r<.28?{type:'Rain',icon:'🌧️',until:300+Math.random()*420}:r<.48?{type:'Cloudy',icon:'☁️',until:360+Math.random()*420}:{type:'Clear',icon:'☀️',until:400+Math.random()*520}}

function townScore(){return Math.min(5,1+Math.floor((player.museum.length+player.placedFurniture.length*2+gardens.length+Math.floor(Object.values(friendship).reduce((a,b)=>a+b,0)/25)+Object.values(townWorks).filter(Boolean).length*5)/12))}
function storyText(){const texts=["Juniper found an old brass key in the museum archive. Raise the island to 2 stars and befriend Pip to learn what it opens.","Pip remembers a sealed path above High Meadow. Build the public stairs and reach 3 stars.","Beyond the ridge sits Cozy Cove’s abandoned lighthouse. Gather 8 wood and 6 stone, then restore it from Town Hall.","The lighthouse shines again. Reach a 5-star island to finish Cozy Cove’s first story chapter.","Chapter I complete: The Light Returns. The villagers now remember you as the neighbor who brought the Cove back together."] ;return texts[Math.min(storyStage,4)]}
function checkStory(){if(storyStage===0&&townScore()>=2&&(friendship.Pip||0)>=20){storyStage=1;toast('Story advanced · Pip remembers the High Meadow path!')}if(storyStage===1&&townWorks.stairs&&townScore()>=3){storyStage=2;toast('Story advanced · The old lighthouse has been found!')}if(storyStage===3&&townScore()>=5){storyStage=4;player.coins+=1000;toast('Chapter I complete · +✦1000!')}save()}
function buildWork(kind){const costs={bridge:{coins:900,wood:8,stone:4},stairs:{coins:1200,wood:6,stone:8},lighthouse:{coins:1600,wood:8,stone:6}}[kind];if(townWorks[kind])return;if(player.coins<costs.coins||player.materials.wood<costs.wood||player.materials.stone<costs.stone){toast('Not enough shells or building materials');return}player.coins-=costs.coins;player.materials.wood-=costs.wood;player.materials.stone-=costs.stone;townWorks[kind]=true;if(kind==='lighthouse'&&storyStage===2)storyStage=3;toast(`${kind[0].toUpperCase()+kind.slice(1)} project complete!`);renderTown();checkStory();save()}
window.buildWork=buildWork;
const recipes=[{name:'Pear Tart',icon:'🥧',needs:['Fruit','Crop'],value:240},{name:'Garden Stew',icon:'🍲',needs:['Crop','Crop'],value:310},{name:'Seaside Plate',icon:'🍱',needs:['Fish','Sea'],value:430}];
function cookRecipe(i){const r=recipes[i],used=[];for(const t of r.needs){const ix=player.inventory.findIndex((x,j)=>x.type===t&&!used.includes(j));if(ix<0){toast(`Need: ${r.needs.join(' + ')}`);return}used.push(ix)}used.sort((a,b)=>b-a).forEach(ix=>player.inventory.splice(ix,1));addItem({name:r.name,icon:r.icon,rarity:'Crafted',value:r.value,type:'Meal',id:itemId()});cooked++;toast(`Cooked ${r.name}!`);renderCook();renderInventory();save()}
window.cookRecipe=cookRecipe;
function renderCook(){document.getElementById('cookGrid').innerHTML=recipes.map((r,i)=>`<div class="card"><div class="icon">${r.icon}</div><h3>${r.name}</h3><p>${r.needs.join(' + ')} · Sell ✦ ${r.value}</p><button onclick="cookRecipe(${i})">Cook</button></div>`).join('')}
function renderTown(){checkStory();const score=townScore();document.getElementById('townRating').innerHTML=`<div class="stars">${'★'.repeat(score)}${'☆'.repeat(5-score)}</div><div>${score}-Star Cozy Cove · Museum ${player.museum.length}/${allCatalog.length} · ${cooked} meals cooked</div>`;document.getElementById('storyCard').innerHTML=`<b>Chapter I · The Light Returns</b><p>${storyText()}</p>`;const data=[['bridge','Creek Bridge','🪵',900],['stairs','High Meadow Stairs','🪜',1200],['lighthouse','Restore Lighthouse','🗼',1600]];document.getElementById('worksGrid').innerHTML=data.map(([k,n,ic,c])=>`<div class="card publicWork"><div class="icon">${ic}</div><h3>${n}</h3><p>✦ ${c} · wood + stone</p><button ${townWorks[k]?'disabled':''} onclick="buildWork('${k}')">${townWorks[k]?'Built':'Build'}</button></div>`).join('')}
function rememberNPC(n){npcMemories[n.name]=npcMemories[n.name]||{talks:0,lastDay:0};const m=npcMemories[n.name];m.talks++;const gap=day-m.lastDay;m.lastDay=day;if(m.talks===3)return `You know, I’m getting used to seeing you around. It makes the Cove feel more like home.`;if(gap>=3)return `It’s been a few days! I was wondering when I’d see you again.`;if(townWorks.lighthouse&&n.name==='Juniper')return `That lighthouse beam is visible from the archive windows. You changed the skyline of this island.`;return null}
function gamepadUpdate(){const gp=navigator.getGamepads?.()[0];if(!gp||modal)return;const ax=gp.axes[0]||0,ay=gp.axes[1]||0;if(Math.abs(ax)>.22)keys[ax>0?'d':'a']=true;if(Math.abs(ay)>.22)keys[ay>0?'s':'w']=true;const now=performance.now();if(now-lastGamepadAction>260){if(gp.buttons[0]?.pressed){interact();lastGamepadAction=now}else if(gp.buttons[2]?.pressed){cast();lastGamepadAction=now}else if(gp.buttons[3]?.pressed){catchBug();lastGamepadAction=now}}}
function toggle(id){const e=document.getElementById(id),willOpen=e.classList.contains('hidden');document.querySelectorAll('.sheet').forEach(x=>x.classList.add('hidden'));if(willOpen)e.classList.remove('hidden');modal=willOpen;if(id==='inventory')renderInventory();if(id==='museum')renderMuseum();if(id==='shop')renderShop();if(id==='journal')renderJournal();if(id==='home')renderHome();if(id==='mapPanel')renderMap();if(id==='craft')renderCraft();if(id==='wardrobe')renderWardrobe();if(id==='farm')renderFarm();if(id==='town')renderTown();if(id==='cook')renderCook()}
function renderInventory(){const g=document.getElementById('inventoryGrid');document.getElementById('bagCount').textContent=`${player.inventory.length} / ${24+(player.bagLevel||0)*8} items`;if(!player.inventory.length){g.innerHTML='<div class="empty">Your backpack is empty. Fish the shore, chase butterflies, or look for fossil cracks.</div>';return}g.innerHTML=player.inventory.map((it,i)=>`<div class="card"><span class="tag" style="color:${rarityColor(it.rarity)}">${it.rarity}</span><div class="icon">${it.icon}</div><h3>${it.name}</h3><p>${it.type} · Sell ✦ ${it.value}</p><button onclick="donate(${i})">Donate</button><button class="alt" onclick="sell(${i})">Sell</button></div>`).join('')}
function renderMuseum(){const got=player.museum.length;document.getElementById('museumSummary').textContent=`${got} of ${allCatalog.length} known specimens donated · ${Math.round(got/allCatalog.length*100)}% complete`;const list=museumTab==='All'?allCatalog:allCatalog.filter(x=>x.type===museumTab);document.getElementById('museumGrid').innerHTML=list.map(it=>{const owned=player.museum.some(x=>x.name===it.name);return `<div class="card" style="opacity:${owned?1:.48}"><span class="tag">${it.type}</span><div class="icon">${owned?it.icon:'❔'}</div><h3>${owned?it.name:'Undiscovered'}</h3><p>${owned?`${it.rarity} specimen`:'Keep exploring to discover this species.'}</p></div>`}).join('')}
function renderShop(){const stock=dailyShopItems();document.getElementById('shopGrid').innerHTML=stock.map(f=>{const i=furnitureCatalog.indexOf(f),owned=player.ownedFurniture.some(x=>x.name===f.name);return `<div class="card"><span class="tag">Day ${day}</span><div class="icon">${f.icon}</div><h3>${f.name}</h3><p>Rotating furniture · ✦ ${f.price}</p><button ${owned?'disabled':''} onclick="buyFurniture(${i})">${owned?'Owned':'Buy'}</button></div>`}).join('')+`<div class="card"><div class="icon">🌱</div><h3>Seed Pack ×5</h3><p>Daily garden supply · ✦ 80</p><button onclick="buySeeds()">Buy</button></div>`;const s=document.getElementById('sellGrid');s.innerHTML=player.inventory.length?player.inventory.map((it,i)=>`<div class="card"><div class="icon">${it.icon}</div><h3>${it.name}</h3><p>Bruno offers ✦ ${it.value}</p><button onclick="sell(${i})">Sell</button></div>`).join(''):'<div class="empty">Nothing to sell yet.</div>'}
function renderJournal(){document.getElementById('journalStats').innerHTML=`<div class="stat"><strong>${player.museum.length}/${allCatalog.length}</strong><span>Museum</span></div><div class="stat"><strong>${player.totalCaught}</strong><span>Finds</span></div><div class="stat"><strong>✦ ${player.totalSold}</strong><span>Sold</span></div><div class="stat"><strong>${player.harvested||0}</strong><span>Harvests</span></div>`;document.getElementById('friendsGrid').innerHTML=npcs.map(n=>`<div class="card"><div class="icon">${n.emoji}</div><h3>${n.name}</h3><p>Friendship ${friendship[n.name]||0}/100 · <span class="npcSchedule">${n.scheduleLabel||npcSchedule(n).label}</span></p><div class="friendMeter"><i style="width:${friendship[n.name]||0}%"></i></div></div>`).join('');const rs=Object.entries(requests).filter(([,r])=>!r.done);document.getElementById('requestsGrid').innerHTML=rs.length?rs.map(([name,r])=>`<div class="card"><h3>${name}</h3><p>Bring any ${r.type.toLowerCase()} · Reward ✦ ${r.reward}</p></div>`).join(''):'<div class="empty">Talk to neighbors to discover requests.</div>'}
function renderHome(){const ext=document.getElementById('exteriorGrid');if(ext){const styles=[['Coastal','#537c96','#f0d6b3'],['Meadow','#6f8d7e','#efe3c2'],['Berry','#ad6685','#f2d8dc'],['Sunset','#c9824f','#f2dfb2']];ext.innerHTML=styles.map(s=>`<button class="styleChoice ${player.houseStyle?.roof===s[1]?'active':''}" onclick="setExterior('${s[1]}','${s[2]}')">${s[0]}</button>`).join('')}const g=document.getElementById('homeGrid');const cost=player.homeLevel>=3?0:650*player.homeLevel;const label=document.getElementById('homeLevelLabel'),txt=document.getElementById('homeUpgradeText'),btn=document.getElementById('upgradeHome');if(label)label.textContent=`Cottage Level ${player.homeLevel}`;if(txt)txt.textContent=player.homeLevel>=3?'Your cottage is fully expanded.':`Next expansion: ✦ ${cost} · ${4+(player.homeLevel+1)*2} furniture slots`;if(btn){btn.textContent=player.homeLevel>=3?'Max Level':`Upgrade · ✦ ${cost}`;btn.disabled=player.homeLevel>=3;} if(!player.ownedFurniture.length){g.innerHTML='<div class="empty">You do not own furniture yet. Visit Bruno’s Boardwalk shop.</div>';return}g.innerHTML=player.ownedFurniture.map((f,i)=>{const placed=player.placedFurniture.some(x=>x.name===f.name);return `<div class="card"><div class="icon">${f.icon}</div><h3>${f.name}</h3><p>${placed?'Currently placed':'In storage'}</p><button onclick="placeFurniture(${i})">${placed?'Store':'Place'}</button></div>`}).join('')}
function renderMap(){const c=document.getElementById('miniMap'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const grd=x.createLinearGradient(0,0,0,c.height);grd.addColorStop(0,'#91cf78');grd.addColorStop(1,'#71b86c');x.fillStyle=grd;x.fillRect(0,0,c.width,c.height);x.fillStyle='#62b9d2';x.fillRect(0,c.height*.74,c.width,c.height*.26);x.fillStyle='#718a69';x.fillRect(c.width*.76,c.height*.08,c.width*.19,c.height*.18);x.fillStyle='#5f9d61';x.beginPath();x.arc(c.width*.86,c.height*.55,28,0,Math.PI*2);x.fill();x.fillStyle='#d6c69c';x.fillRect(105,170,520,26);x.fillRect(338,95,28,235);houses.forEach(h=>{x.fillStyle=h.museum?'#69778e':h.shop?'#c58f4f':h.playerHome?'#537c96':'#ead7b6';x.fillRect(h.x/world.w*c.width,h.y/world.h*c.height,Math.max(18,h.w/world.w*c.width),Math.max(14,h.h/world.h*c.height))});x.fillStyle='#213f35';x.beginPath();x.arc(player.x/world.w*c.width,player.y/world.h*c.height,7,0,Math.PI*2);x.fill()}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1900)}

for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>{document.getElementById(b.dataset.close).classList.add('hidden');modal=false};
for(const b of document.querySelectorAll('[data-museum-tab]'))b.onclick=()=>{museumTab=b.dataset.museumTab;document.querySelectorAll('[data-museum-tab]').forEach(x=>x.classList.toggle('active',x===b));renderMuseum()};
document.getElementById('upgradeHome').onclick=upgradeHome;document.getElementById('soundToggle').onclick=()=>{soundOn=!soundOn;if(soundOn){initAmbient();if(ambientGain)ambientGain.gain.value=.012;playTone(520,.08,.03)}else if(ambientGain)ambientGain.gain.value=0;document.getElementById('soundToggle').textContent=soundOn?'🔊':'🔇';save()};document.getElementById('soundToggle').textContent=soundOn?'🔊':'🔇';
for(const b of document.querySelectorAll('[data-slot]'))b.onclick=()=>{activeSlot=Number(b.dataset.slot);document.querySelectorAll('[data-slot]').forEach(x=>x.classList.toggle('active',x===b));updateSlotSummary()};
document.getElementById('continueGame').onclick=()=>startGame();document.getElementById('newGame').onclick=()=>{if(confirm('Start a fresh island in this save slot?')){localStorage.removeItem(saveKey());location.reload()}};updateSlotSummary();
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>({interact,fish:cast,bug:catchBug,dig,dive:toggleSwimDive}[b.dataset.action]||(()=>{}))();
addEventListener('keydown',e=>{initAmbient();keys[e.key]=true;if(e.repeat)return;const k=e.key.toLowerCase();if(k==='e')interact();if(k==='f')cast();if(k==='b')catchBug();if(k==='x')dig();if(k==='g')plant();if(k==='z')gather();if(k==='v')toggleSwimDive();if(k==='c')toggle('craft');if(k==='r')toggle('wardrobe');if(k==='t')toggle('farm');if(k==='l')toggle('town');if(k==='k')toggle('cook');if(k==='i')toggle('inventory');if(k==='m')toggle('mapPanel');if(k==='q')toggle('journal');if(k==='h'){if(interior==='You')toggle('home');else toast('Open Home Designer from inside your cottage')}if(e.key==='Escape'){document.querySelectorAll('.sheet,#dialogue').forEach(x=>x.classList.add('hidden'));modal=false}});addEventListener('keyup',e=>keys[e.key]=false);
canvas.addEventListener('pointerdown',e=>{if(modal||interior)return;const r=canvas.getBoundingClientRect(),wx=e.clientX-r.left+camera.x,wy=e.clientY-r.top+camera.y,dx=wx-player.x,dy=wy-player.y,l=Math.hypot(dx,dy);if(l>10){player.x+=dx/l*Math.min(l,60);player.y+=dy/l*Math.min(l,60)}});
function loop(now){gamepadUpdate();keys.a=keys.a&&!(navigator.getGamepads?.()[0]);keys.d=keys.d&&!(navigator.getGamepads?.()[0]);keys.w=keys.w&&!(navigator.getGamepads?.()[0]);keys.s=keys.s&&!(navigator.getGamepads?.()[0]);const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}
renderInventory();renderMuseum();renderShop();renderJournal();renderHome();renderCraft();renderWardrobe();renderFarm();renderCook();renderTown();requestAnimationFrame(loop);
})();
