/**
 * Regenerates ASSET_CREDITS.md from the manifest.
 *
 * Generated rather than hand-written so the credits cannot drift away from what
 * the game actually ships: adding a kit to `manifest.ts` and forgetting to
 * credit it is not possible if the credits are derived from the manifest.
 */
import { writeFileSync } from 'node:fs';
import { KITS, MODELS } from '../src/assets/manifest';
import { SOUNDS } from '../src/audio/sounds';

/**
 * Audio packs, with the exact files taken from each.
 *
 * Listed per file rather than per pack so the credits can only name a pack the
 * game actually plays. An earlier version hardcoded the pack list, which meant
 * the table credited packs that had been planned but never shipped.
 */
const AUDIO_PACKS: { pack: string; url: string; licence: string; files: string[] }[] = [
  {
    pack: 'Kenney — Impact Sounds',
    url: 'https://kenney.nl/assets/impact-sounds',
    licence: 'CC0 1.0',
    files: ['footstep_grass_000.ogg', 'footstep_carpet_000.ogg', 'footstep_wood_000.ogg', 'footstep_concrete_000.ogg'],
  },
  {
    pack: 'Kenney — RPG Audio',
    url: 'https://kenney.nl/assets/rpg-audio',
    licence: 'CC0 1.0',
    files: ['cloth3.ogg', 'chop.ogg'],
  },
  {
    pack: 'Kenney — Interface Sounds',
    url: 'https://kenney.nl/assets/interface-sounds',
    licence: 'CC0 1.0',
    files: ['click_001.ogg', 'back_001.ogg'],
  },
];

const shippedAudio = SOUNDS.flatMap((sound) => (sound.src ? [sound.src] : []));
const basename = (path: string): string => path.slice(path.lastIndexOf('/') + 1);

// A shipped sound with no pack entry would appear in the game uncredited and,
// worse, untraceable back to a licence file. Fail the build rather than emit
// credits that are quietly incomplete.
const unattributed = shippedAudio.filter(
  (src) => !AUDIO_PACKS.some((entry) => entry.files.includes(basename(src))),
);
if (unattributed.length > 0) {
  console.error(`Unattributed audio (add it to AUDIO_PACKS in tools/genCredits.ts):\n  ${unattributed.join('\n  ')}`);
  process.exit(1);
}

const LICENCE_TEXT: Record<string, { name: string; url: string; attribution: string }> = {
  'CC0-1.0': {
    name: 'CC0 1.0 Universal (public domain dedication)',
    url: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: 'not required',
  },
};

const modelCount = new Map<string, number>();
for (const model of MODELS) {
  modelCount.set(model.kit, (modelCount.get(model.kit) ?? 0) + 1);
}

const lines: string[] = [
  '# Asset Credits',
  '',
  '<!-- Generated by `npm run assets:credits`. Edit src/assets/manifest.ts, not this file. -->',
  '',
  'Every asset bundled with Cozy Cove, its creator, and its licence.',
  '',
  'The project deliberately ships **CC0 art and audio only**, so no attribution is',
  'legally required for any model or sound listed here. The credits are kept',
  'anyway: the people below made this game look and sound like something, and',
  'that is worth writing down.',
  '',
  'The one exception is the UI font, under SIL OFL 1.1, which does carry a',
  'condition — its `OFL.txt` ships in `licenses/`.',
  '',
  '## 3D models',
  '',
];

if (MODELS.length === 0) {
  lines.push(
    '_No models bundled yet._ The kits below are the approved sources from',
    '`docs/ASSET_PLAN.md`; models are added to `src/assets/manifest.ts` as each',
    'pack is downloaded, verified and optimised.',
    '',
  );
}

lines.push('| Kit | Source | Licence | Attribution | Models in use |', '| --- | --- | --- | --- | --- |');
for (const kit of KITS) {
  const licence = LICENCE_TEXT[kit.licence];
  const used = modelCount.get(kit.id) ?? 0;
  lines.push(
    `| \`${kit.id}\` | ${kit.source} | [${licence.name}](${licence.url}) | ${licence.attribution} | ${used || '—'} |`,
  );
}

lines.push(
  '',
  '## Audio',
  '',
  'Sound effects and music are declared in `src/audio/sounds.ts`. Entries still',
  'using the built-in synthesiser have no external source to credit; only packs',
  'the game actually plays a file from appear below.',
  '',
  '| Pack | Source | Licence | Attribution | Sounds in use |',
  '| --- | --- | --- | --- | --- |',
);

for (const entry of AUDIO_PACKS) {
  const used = shippedAudio.filter((src) => entry.files.includes(basename(src))).length;
  if (used === 0) continue;
  lines.push(`| ${entry.pack} | ${entry.url} | ${entry.licence} | not required | ${used} |`);
}

lines.push(
  '',
  '## Licence files',
  '',
  'Each pack\'s original, unedited licence text is preserved under `licenses/`.',
  'Those files are the authoritative record; this page is a summary of them.',
  '',
);

writeFileSync('ASSET_CREDITS.md', `${lines.join('\n')}`);
console.log(`ASSET_CREDITS.md written — ${KITS.length} kits, ${MODELS.length} models.`);
