/**
 * Regenerates ASSET_CREDITS.md from the manifest.
 *
 * Generated rather than hand-written so the credits cannot drift away from what
 * the game actually ships: adding a kit to `manifest.ts` and forgetting to
 * credit it is not possible if the credits are derived from the manifest.
 */
import { writeFileSync } from 'node:fs';
import { KITS, MODELS } from '../src/assets/manifest';

const LICENCE_TEXT: Record<string, { name: string; url: string; attribution: string }> = {
  'CC0-1.0': {
    name: 'CC0 1.0 Universal (public domain dedication)',
    url: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: 'not required',
  },
};

const modelCount = new Map<string, number>();
for (const model of MODELS) {
  modelCount.set(model.kit, (modelCount.get(model.kit) ?? 0) + 1);
}

const lines: string[] = [
  '# Asset Credits',
  '',
  '<!-- Generated by `npm run assets:credits`. Edit src/assets/manifest.ts, not this file. -->',
  '',
  'Every asset bundled with Cozy Cove, its creator, and its licence.',
  '',
  'The project deliberately ships **CC0 art and audio only**, so no attribution is',
  'legally required for any model or sound listed here. The credits are kept',
  'anyway: the people below made this game look and sound like something, and',
  'that is worth writing down.',
  '',
  'The one exception is the UI font, under SIL OFL 1.1, which does carry a',
  'condition — its `OFL.txt` ships in `licenses/`.',
  '',
  '## 3D models',
  '',
];

if (MODELS.length === 0) {
  lines.push(
    '_No models bundled yet._ The kits below are the approved sources from',
    '`docs/ASSET_PLAN.md`; models are added to `src/assets/manifest.ts` as each',
    'pack is downloaded, verified and optimised.',
    '',
  );
}

lines.push('| Kit | Source | Licence | Attribution | Models in use |', '| --- | --- | --- | --- | --- |');
for (const kit of KITS) {
  const licence = LICENCE_TEXT[kit.licence];
  const used = modelCount.get(kit.id) ?? 0;
  lines.push(
    `| \`${kit.id}\` | ${kit.source} | [${licence.name}](${licence.url}) | ${licence.attribution} | ${used || '—'} |`,
  );
}

lines.push(
  '',
  '## Audio',
  '',
  'Sound effects and music are declared in `src/audio/sounds.ts`. Entries still',
  'using the built-in synthesiser have no external source to credit; entries with',
  'a `src` path are listed here once they land.',
  '',
  '| Pack | Source | Licence | Attribution |',
  '| --- | --- | --- | --- |',
  '| Kenney — RPG Audio | https://kenney.nl/assets/rpg-audio | CC0 1.0 | not required |',
  '| Kenney — Interface Sounds | https://kenney.nl/assets/interface-sounds | CC0 1.0 | not required |',
  '| Kenney — Impact Sounds | https://kenney.nl/assets/impact-sounds | CC0 1.0 | not required |',
  '| Tallbeard Studios — Music Loop Bundle | https://tallbeard.itch.io/music-loop-bundle | CC0 | not required |',
  '',
  '## Licence files',
  '',
  'Each pack\'s original, unedited licence text is preserved under `licenses/`.',
  'Those files are the authoritative record; this page is a summary of them.',
  '',
);

writeFileSync('ASSET_CREDITS.md', `${lines.join('\n')}`);
console.log(`ASSET_CREDITS.md written — ${KITS.length} kits, ${MODELS.length} models.`);
